### ISSUE TITLE
📦 NEW: Add sell command

### ISSUE THREAD

**Issue by ianagbip1oti** [ianagbip1oti/greedorama#1]
The buy command already exists, and a sell should work pretty much like a negative buy.

**Comment by ghost** [comment]
Basically this, since greedorama is not using real time prices?
- [ ] Reduce stock by 1, add single stock price to CASH.
- [ ] If stock is 0 after reduce, remove stock from portfolio.

**Comment by ianagbip1oti** [comment]
A Portfolio is defined by it's history of transactions. So, it should be sufficient to start add the sell transaction. I'm thinking it will just be the same as a buy, but with a negative amount.

**Comment by ianagbip1oti** [comment]
Done in #21
